// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/CarPlayAlert.tsx": () => import("../components/mockups/CarPlayAlert.tsx"),
  "./components/mockups/CarPlayIdle.tsx": () => import("../components/mockups/CarPlayIdle.tsx"),
  "./components/mockups/CarPlayList.tsx": () => import("../components/mockups/CarPlayList.tsx"),
  "./components/mockups/CarPlayNav.tsx": () => import("../components/mockups/CarPlayNav.tsx"),
  "./components/mockups/CarPlayScreens.tsx": () => import("../components/mockups/CarPlayScreens.tsx"),
  "./components/mockups/carplay-active/MemberAlert.tsx": () => import("../components/mockups/carplay-active/MemberAlert.tsx"),
  "./components/mockups/carplay-active/Navigating.tsx": () => import("../components/mockups/carplay-active/Navigating.tsx"),
  "./components/mockups/carplay-active/Overview.tsx": () => import("../components/mockups/carplay-active/Overview.tsx"),
  "./components/mockups/carplay-active/PTTActive.tsx": () => import("../components/mockups/carplay-active/PTTActive.tsx"),
  "./components/mockups/carplay-auth/Authenticated.tsx": () => import("../components/mockups/carplay-auth/Authenticated.tsx"),
  "./components/mockups/carplay-auth/Connecting.tsx": () => import("../components/mockups/carplay-auth/Connecting.tsx"),
  "./components/mockups/carplay-auth/NotConnected.tsx": () => import("../components/mockups/carplay-auth/NotConnected.tsx"),
  "./components/mockups/maps/IdleView.tsx": () => import("../components/mockups/maps/IdleView.tsx"),
  "./components/mockups/maps/NavigatingView.tsx": () => import("../components/mockups/maps/NavigatingView.tsx"),
  "./components/mockups/maps/RightSidebar.tsx": () => import("../components/mockups/maps/RightSidebar.tsx")
};
